/**
 * Exports the current database into plain SQL:
 *
 *   db/schema.sql   DDL (copied from the Prisma migration)
 *   db/seed.sql     INSERT statements for every catalogue row
 *
 * The app itself does not need these - Prisma migrate + `npm run db:seed`
 * cover the whole flow - but they let anyone stand the database up with
 * `psql -f` and read the schema without knowing Prisma.
 *
 *   npm run db:export
 */

import { mkdir, readFile, readdir, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

import { PrismaClient } from "@prisma/client";

const HERE = dirname(fileURLToPath(import.meta.url));
const ROOT = join(HERE, "..");
const OUT_DIR = join(ROOT, "db");
const MIGRATIONS_DIR = join(ROOT, "prisma", "migrations");

const prisma = new PrismaClient();

type Row = Record<string, unknown>;

function literal(value: unknown): string {
  if (value === null || value === undefined) return "NULL";
  if (typeof value === "number") return String(value);
  if (typeof value === "boolean") return value ? "TRUE" : "FALSE";
  if (value instanceof Date) return `'${value.toISOString()}'`;
  return `'${String(value).replace(/'/g, "''")}'`;
}

function insertStatements(table: string, rows: Row[], columns: string[]): string {
  if (rows.length === 0) return `-- ${table}: no rows\n`;

  const columnList = columns.map((c) => `"${c}"`).join(", ");
  const values = rows
    .map((row) => `  (${columns.map((column) => literal(row[column])).join(", ")})`)
    .join(",\n");

  return `INSERT INTO "${table}" (${columnList}) VALUES\n${values}\nON CONFLICT DO NOTHING;\n`;
}

async function exportSchema(): Promise<void> {
  const entries = (await readdir(MIGRATIONS_DIR, { withFileTypes: true }))
    .filter((entry) => entry.isDirectory())
    .map((entry) => entry.name)
    .sort();

  const parts: string[] = [
    "-- ---------------------------------------------------------------------------",
    "-- 1Fi EMI Store - PostgreSQL schema",
    "--",
    "-- Generated from the Prisma migrations (`npm run db:export`).",
    "-- Money columns are integer paise; rates are integer basis points.",
    "--",
    "-- Apply with:  psql \"$DATABASE_URL\" -f db/schema.sql",
    "-- ---------------------------------------------------------------------------",
    "",
  ];

  for (const entry of entries) {
    const sql = await readFile(join(MIGRATIONS_DIR, entry, "migration.sql"), "utf8");
    parts.push(`-- migration: ${entry}`, sql.trim(), "");
  }

  await writeFile(join(OUT_DIR, "schema.sql"), parts.join("\n"), "utf8");
  console.log(`  db/schema.sql   <- ${entries.length} migration(s)`);
}

async function exportSeed(): Promise<void> {
  const [funds, products, highlights, variants, images, plans] = await Promise.all([
    prisma.mutualFund.findMany({ orderBy: { code: "asc" } }),
    prisma.product.findMany({ orderBy: { position: "asc" } }),
    prisma.productHighlight.findMany({ orderBy: [{ productId: "asc" }, { position: "asc" }] }),
    prisma.variant.findMany({ orderBy: [{ productId: "asc" }, { position: "asc" }] }),
    prisma.variantImage.findMany({ orderBy: [{ variantId: "asc" }, { position: "asc" }] }),
    prisma.emiPlan.findMany({ orderBy: [{ productId: "asc" }, { position: "asc" }] }),
  ]);

  const sections = [
    insertStatements("mutual_funds", funds, [
      "id",
      "code",
      "name",
      "amc",
      "category",
      "expectedReturnBps",
      "riskLevel",
    ]),
    insertStatements("products", products, [
      "id",
      "slug",
      "name",
      "brand",
      "category",
      "tagline",
      "description",
      "isNew",
      "position",
      "isActive",
      "createdAt",
      "updatedAt",
    ]),
    insertStatements("product_highlights", highlights, [
      "id",
      "productId",
      "label",
      "value",
      "position",
    ]),
    insertStatements("variants", variants, [
      "id",
      "productId",
      "slug",
      "sku",
      "colorName",
      "colorHex",
      "storage",
      "mrpPaise",
      "pricePaise",
      "inStock",
      "isDefault",
      "position",
      "createdAt",
      "updatedAt",
    ]),
    insertStatements("variant_images", images, ["id", "variantId", "url", "alt", "position"]),
    insertStatements("emi_plans", plans, [
      "id",
      "productId",
      "fundId",
      "tenureMonths",
      "interestRateBps",
      "cashbackPaise",
      "processingFeePaise",
      "isRecommended",
      "isActive",
      "position",
      "createdAt",
      "updatedAt",
    ]),
  ];

  const header = [
    "-- ---------------------------------------------------------------------------",
    "-- 1Fi EMI Store - seed data",
    "--",
    "-- Generated by `npm run db:export`. Run db/schema.sql first.",
    `-- ${products.length} products, ${variants.length} variants, ${plans.length} EMI plans,`,
    `-- ${funds.length} mutual funds, ${images.length} images.`,
    "--",
    "-- Apply with:  psql \"$DATABASE_URL\" -f db/seed.sql",
    "-- ---------------------------------------------------------------------------",
    "",
    "BEGIN;",
    "",
  ].join("\n");

  await writeFile(join(OUT_DIR, "seed.sql"), `${header}${sections.join("\n")}\nCOMMIT;\n`, "utf8");
  console.log(
    `  db/seed.sql     <- ${funds.length} funds, ${products.length} products, ` +
      `${variants.length} variants, ${images.length} images, ${plans.length} plans`,
  );
}

async function main() {
  await mkdir(OUT_DIR, { recursive: true });
  console.log("Exporting SQL...");
  await exportSchema();
  await exportSeed();
}

main()
  .catch((error) => {
    console.error(error);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
